# Generated by Django 5.0.6 on 2024-05-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='quantidade',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='produto',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.product'),
            preserve_default=False,
        ),
    ]
