# Generated by Django 5.0.6 on 2024-05-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_quantidade_orderproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accomplished', 'Realizado'), ('Preparation', 'Preparando'), ('Cancelled', 'Cancelado'), ('Ready', 'Pronto'), ('Closed', 'Fechado')], default='accomplished', max_length=20),
        ),
    ]
