# Generated by Django 5.0.6 on 2024-05-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accomplished', 'Realizado'), ('Preparation', 'Preparando'), ('Cancelled', 'Cancelado'), ('Ready', 'Pronto')], default='accomplished', max_length=20),
        ),
    ]
