# Generated by Django 5.0.6 on 2024-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Paga')], default='pending', max_length=7),
        ),
    ]
