# Generated by Django 5.0.6 on 2024-06-04 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_bill_generated_at_bill_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Preparing', 'Preparando'), ('Ready', 'Pronto')], default='Preparing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chef', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'waiter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders', to=settings.AUTH_USER_MODEL)),
                ('order_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='orders.orderproduct')),
            ],
            options={
                'verbose_name': 'Cozinha',
                'verbose_name_plural': 'Cozinhas',
            },
        ),
    ]
