# Generated by Django 5.0.6 on 2024-06-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_product_type_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelada'), ('Closed', 'Fechada'), ('Open', 'Aberta')], default='Open', max_length=20),
        ),
    ]
