# Generated by Django 5.0.6 on 2024-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Gerente'), ('waiter', 'Garçom'), ('kitchen', 'Cozinha'), ('box', 'Caixa')], max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
